fp-topics/hendelser-vedtatt-ytelse/pom.xml, pom.xml, vl-kontrakt-registerdata-callback/README.md, vl-kontrakt-registerdata-callback/pom.xml, vl-kontrakt-registerdata-callback/src/main/java/no/nav/foreldrepenger/kontrakter/callback/registerdata/CallbackDto.java, vl-kontrakt-registerdata-callback/src/main/java/no/nav/foreldrepenger/kontrakter/callback/registerdata/Grunnlag.java, vl-kontrakt-registerdata-callback/src/main/java/no/nav/foreldrepenger/kontrakter/callback/registerdata/ReferanseDto.java, vl-kontrakt-registerdata-callback/src/test/java/no/nav/foreldrepenger/kontrakter/callback/registerdata/ReferanseDtoTest.java
Kontrakt for callback til fpsak ved registerdata i ekstern system som… prosessen i fpsak er avhengig av eller ønsker å vite om.
=> Callback kontrakt

fp-topics/hendelser-kontroll-resultat/pom.xml, fp-topics/hendelser-kontroll-resultat/src/main/java/no/nav/vedtak/kontroll/KontrollResultat.java, fp-topics/hendelser-kontroll-resultat/src/main/java/no/nav/vedtak/kontroll/kodeverk/Kodeverk.java, fp-topics/hendelser-kontroll-resultat/src/main/java/no/nav/vedtak/kontroll/kodeverk/KontrollResultatkode.java, fp-topics/hendelser-kontroll-resultat/src/main/java/no/nav/vedtak/kontroll/v1/KontrollResultatV1.java, fp-topics/manifest/src/main/java/no/nav/familie/topic/TopicManifest.java, fp-topics/pom.xml
Usikker på om det er noe mer som trengs for at dette skal fungere? Så ikke noe mer som var i bruk i fpsak for de eksisterende topicsa
=> PFP-8262: Kontrakt for kontrollresultatet

vl-kontrakt-iaygrunnlag/src/main/java/no/nav/foreldrepenger/kontrakter/iaygrunnlag/oppgittopptjening/v1/OppgittEgenNæringDto.java
=> FIX tillatt | i navn og telefonnr

Jenkinsfile
This reverts commit da84ae1480eb98047dabf8fa5525471ea084b5b8.
=> Revert "Create Jenkinsfile (#112)"

vl-kontrakt-fordel/src/main/java/no/nav/foreldrepenger/kontrakter/fordel/VurderFagsystemDto.java
ArbeidsforholdsId med "," som manglet i strengvalidering
=> TFP-1256 utvid arbeidsforholdsvalidering med komma

vl-kontrakt-fordel/src/main/java/no/nav/foreldrepenger/kontrakter/fordel/JournalpostMottakDto.java
=> FIX fordel-fpsak støtte ny maxi søknad

fp-topics/hendelser-behandlingsprosess/src/main/java/no/nav/vedtak/felles/integrasjon/kafka/TilbakebetalingBehandlingProsessEventDto.java, fp-topics/hendelser-behandlingsprosess/src/test/java/no/nav/vedtak/felles/integrasjon/kafka/BehandlingProsessEventDtoTest.java
La til et felt for å sette saksbehandlerident mtp filtrering i behandler-køer.
=> TFP-1674 Tilbakebetaling ønsker å sende saksbehandlerident

CODEOWNERS, pom.xml, vl-kontrakt-oekonomi/grensesnittavstemming-v1/README.md, vl-kontrakt-oekonomi/grensesnittavstemming-v1/pom.xml, vl-kontrakt-oekonomi/grensesnittavstemming-v1/src/main/java/no/nav/foreldrepenger/integrasjon/økonomistøtte/grensesnittavstemming/GrensesnittavstemmingSkjemaConstants.java, vl-kontrakt-oekonomi/grensesnittavstemming-v1/src/main/resources/xsd-original/grensesnittavstemmingskjema-v1.xsd, vl-kontrakt-oekonomi/grensesnittavstemming-v1/src/main/resources/xsd/grensesnittavstemmingskjema-v1.xsd, vl-kontrakt-oekonomi/grensesnittavstemming-v1/src/test/java/no/nav/foreldrepenger/integrasjon/økonomistøtte/grensesnittavstemming/GrensesnittavstemmingSkjemaConstantsTest.java, vl-kontrakt-oekonomi/grensesnittavstemming-v1/src/test/java/no/nav/foreldrepenger/integrasjon/økonomistøtte/grensesnittavstemming/XmlUtils.java, vl-kontrakt-oekonomi/oppdragskjema-v1/README.md, vl-kontrakt-oekonomi/oppdragskjema-v1/pom.xml, vl-kontrakt-oekonomi/oppdragskjema-v1/src/main/java/no/nav/foreldrepenger/integrasjon/økonomistøtte/oppdrag/OppdragSkjemaConstants.java, vl-kontrakt-oekonomi/oppdragskjema-v1/src/main/resources/xsd/oppdragskjema-v1.xsd, vl-kontrakt-oekonomi/oppdragskjema-v1/src/test/java/no/nav/foreldrepenger/integrasjon/økonomistøtte/oppdrag/OppdragSkjemaConstantsTest.java, vl-kontrakt-oekonomi/oppdragskjema-v1/src/test/java/no/nav/foreldrepenger/integrasjon/økonomistøtte/oppdrag/XmlUtils.java, vl-kontrakt-oekonomi/pom.xml
Grensesnittavstemming v1
Oppdragskjema v1
=> Kontrakter fra stash

pom.xml
Reverts navikt/fp-kontrakter#202
=> Revert "Bump jaxb-runtime from 2.4.0-b180830.0438 to 3.0.0-M3"

README.md
Reverts navikt/fp-kontrakter#258
=> Revert "Trigge ny relase pga feil"

pom.xml, vl-kontrakt-fp-abonnent/src/main/java/no/nav/foreldrepenger/kontrakter/abonnent/v2/HendelseDto.java, vl-kontrakt-fp-abonnent/src/main/java/no/nav/foreldrepenger/kontrakter/abonnent/v2/pdl/AdressebeskyttelseHendelseDto.java, vl-kontrakt-fp-risk/pom.xml, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/kodeverk/RisikogruppeType.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/kodeverk/RisikoklasseType.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/kodeverk/YtelseType.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/AnnenPartDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/HentRisikovurderingDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikogruppeDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingCallbackDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingRequestDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingResultatDto.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingCallbackTest.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingRequestTest.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingResultatTest.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/TestJsonMapper.java
Samle og forenkle kontrakt fpsak-fprisk med sikte på å sanere 2 stk 1-1 topics og bruke Rest.
Pluss adressebskyttelsehendelser fra abonnent
=> Kontrakt for restifisering fpsak-fprisk

vl-kontrakt-soeknad/soeknad-v3/src/main/resources/xsd/kodeverk/kodeverk-v3.xsd
Enkelt navn. Tror ikke det skal mer til enn denne.
=> TFP-4522 ny utsettelsesårsak FRI

vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/kodeverk/AktørId.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/kodeverk/RisikogruppeType.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/AnnenPartDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/HentRisikovurderingDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikogruppeDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingCallbackDto.java, vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingRequestDto.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingRequestTest.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingResultatTest.java
Risk-kontrakt ifm overgang til rest. Tilpasset dagens bruk av data.
=> TFP-4706 oppdatering av risk-kontrakt

vl-kontrakt-soeknad/soeknad-v3/src/main/resources/xsd/felles/felles-v3.xsd, vl-kontrakt-soeknad/soeknad-v3/src/test/java/no/nav/foreldrepenger/søknad/v3/ParseSoeknadTest.java
Utvider med optional felt for oppgitt at mor er uføretrygdet jfr Ftil 14-14 tredje ledd
=> TFP-4794 legg til uføretrygd i søknadxml

pom.xml, vl-kontrakt-fp-formidling/pom.xml, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/formidling/v1/DokumentbestillingDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/formidling/v1/DokumentbestillingV2Dto.java, vl-kontrakt-fp-formidling/src/test/java/no/nav/foreldrepenger/kontrakter/formidling/v1/DokumentbestillingV2Test.java, vl-kontrakt-fp-formidling/src/test/java/no/nav/foreldrepenger/kontrakter/formidling/v1/TestJsonMapper.java
Dokumentbestilling over Kafka har aldri blitt validert av Consumer. Det skjer automatisk med Rest ....
Forhåndsvisning har alltid send null for behandlendeEnhetNavn
=> Riktig validering av behandlende enhet

vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/BeregningsgrunnlagAndelDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/BeregningsgrunnlagDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/BeregningsgrunnlagPeriodeDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/kodeverk/AktivitetStatusDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/kodeverk/HjemmelDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/kodeverk/OpptjeningAktivitetDto.java, vl-kontrakt-fp-formidling/src/main/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/kodeverk/PeriodeÅrsakDto.java, vl-kontrakt-fp-formidling/src/test/java/no/nav/foreldrepenger/kontrakter/fpsak/beregningsgrunnlag/v2/BeregningsgrunnlagDtoTest.java
Sørger for at plain enums blir serialisert som string og ikke objekt.
=> Fjernet shape OBJECT fra kodeverk dtoene. Endret navn.

pom.xml
Reverts navikt/fp-kontrakter#364
=> Revert "Bump jaxb2-maven-plugin from 2.5.0 to 3.1.0"

vl-kontrakt-soeknad/soeknad-v3/src/main/resources/xsd/felles/felles-v3.xsd
Spørsmål i dialog gjelder om annenpart har aktivitet i EØS som ville oppfylt norsk opptjeningsvilkår "Har [annen forelder] arbeidet eller mottatt pengestøtte i et EØS-land i minst seks av de siste ti månedene før barnet ble født?"
Så var det å finne beste navn harAnnenForelderOpptjeningIEOS, harAnnenForelderNokOpptjeningIEOS, harAnnenForelderForeldrepengerIEOS, harAnnenForelderAktivitetIEOS
=> TFP-5159 generalisert søknadsrettighet for annenparts opptjening i EØS

vl-kontrakt-soeknad/soeknad-v3/src/main/resources/xsd/felles/felles-v3.xsd
Skal brukes for å utlede 5068 i stedet for om annen part har tilsvarende rett i eøs
=> Boolean i søknaden fp for om annen part har oppholdt seg i eøs

vl-kontrakt-fp-risk/src/main/java/no/nav/foreldrepenger/kontrakter/risk/v1/AnnenPartDto.java, vl-kontrakt-fp-risk/src/test/java/no/nav/foreldrepenger/kontrakter/risk/v1/RisikovurderingRequestTest.java
Tillate ulike hyphens/dash unicode 2010...2014
=> Tillate unicode punctuation i utlandsk fnr

fp-topics/hendelser-behandling/pom.xml, fp-topics/hendelser-behandling/src/main/java/no/nav/vedtak/hendelser/behandling/Behandlingsårsak.java, fp-topics/hendelser-behandling/src/main/java/no/nav/vedtak/hendelser/behandling/los/LosBehandlingDto.java, pom.xml, vl-kontrakt-fp-abonnent/pom.xml, vl-kontrakt-fp-formidling/pom.xml, vl-kontrakt-fp-risk/pom.xml, vl-kontrakt-simulering-resultat/pom.xml
Teller på knappene om vi skal ta med aksjonspunkt-fagområde
=> Omarbeide Los-Dto, Jakarta ELv5

fp-topics/hendelser-behandling/src/main/java/no/nav/vedtak/hendelser/behandling/los/LosBehandlingDto.java
Merge + relase på dagtid i USA
=> Dummy for å trigge release

vl-kontrakt-soeknad/soeknad-v3/src/main/resources/xsd/svangerskapspenger/svangerskapspenger-v1.xsd, vl-kontrakt-soeknad/soeknad-v3/src/test/java/no/nav/foreldrepenger/søknad/v3/ParseSoeknadTest.java, vl-kontrakt-soeknad/soeknad-v3/src/test/resources/svp-soeknad.xml
Utvider med liste med ferieperioder
=> TFP-5815 svp ferieperioder i soknad 

fp-topics/hendelser-behandling/src/main/java/no/nav/vedtak/hendelser/behandling/Hendelse.java
Til bruk i fpsak når en søknad er mottatt og lagret. 
Skal bruke til å sende beskjed om til mor fra fpoversikt, skal legge inn i ignore i fplos
=> TFP-6060 utvider behandlingshendelser med hendelse for mottatt søknad

vl-kontrakt-fp-ws-proxy/src/main/java/no/nav/foreldrepenger/kontrakter/fpwsproxy/simulering/request/KodeKlassifik.java
This reverts commit 9681c3153e277083a1463f740022b7bc7e8557c6.
=> Revert "Legger til klassekoden UNG-IOP (#628)"
